apiVersion: v1
kind: PersistentVolume
metadata:
  name: laravel-mysql-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysqlvolume"
